import type { Metadata } from "next";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import { ShopProvider } from "@/components/ShopContext";
import { Toaster } from "sonner";
import { AppLayout } from "@/components/layout/AppLayout";
import { ErrorBoundary } from "@/components/common/ErrorBoundary";
import "./globals.css";

export const metadata: Metadata = {
  title: "WooCommerce Product Manager",
  description: "Generated by Medegaard Grafisk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased" suppressHydrationWarning>
        <ErrorBoundary>
          <ShopProvider>
            <AppLayout>
              {children}
            </AppLayout>
            <Toaster richColors position="top-right" />
          </ShopProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
